kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rollouts-blue-green.fullname" . }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
