kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spring-component.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spring-component.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spring-component.fullname" . }}
