apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "config-server.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}