apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: springbootapp
  name: springbootapp
  namespace: dev-apps
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: springbootapp:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM openjdk:11
      COPY app.jar /
      ENTRYPOINT ["java","-jar","/app.jar"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk:11
    type: Docker
  successfulBuildsHistoryLimit: 5
