apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: springbootapp
  name: springbootapp
  namespace: dev-apps
spec:
  lookupPolicy:
    local: false